# Generated by Django 4.0.5 on 2022-06-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True, max_length=30, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_name', models.CharField(max_length=30, verbose_name='Device name')),
                ('ip_address', models.URLField(verbose_name='IP address')),
                ('device_type', models.CharField(max_length=30, verbose_name='Type')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Locate')),
                ('start_state', models.BooleanField(default=False, verbose_name='Start state')),
                ('created_timestamp', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.groups')),
            ],
        ),
    ]
