# Generated by Django 4.0.5 on 2022-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchdevices',
            name='state_now',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
    ]
